name: preluded_music
description: "Preluded Music - Native iOS & Multiplatform Flutter Music Player"
publish_to: 'none'
version: 2.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  just_audio: ^0.9.40
  audio_service: ^0.18.17
  cached_network_image: ^3.4.1
  shared_preferences: ^2.3.3
  http: ^1.2.2
  provider: ^6.1.2
  intl: ^0.19.0
  marquee: ^2.2.3
  palette_generator: ^0.3.3+4
  share_plus: ^10.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
